"""
Knowledge graph construction from repository code intelligence.

This module converts parser-independent analyzer models into a
repository-level directed graph.

Pipeline:

    RepositoryCodeInventory
            |
            v
    KnowledgeGraphBuilder
            |
            v
        CodeGraph

The builder creates deterministic structural relationships.

Responsibilities:
    - Create repository/file/entity nodes
    - Create file-level import relationships
    - Create symbol-level import relationships
    - Create export relationships
    - Create function/method call relationships
    - Preserve unresolved symbols
    - Maintain deterministic graph IDs
    - Keep parser-specific implementation details out of the graph

Ambiguous cross-file call resolution is intentionally left for
resolver.py.
"""

from __future__ import annotations

import logging
import os
from collections import defaultdict
from pathlib import Path

from ..analyzer.models import (
    CallReference,
    CodeEntity,
    CodeEntityType,
    ExportReference,
    ImportReference,
)
from ..analyzer.repository_analyzer import (
    FileAnalysisResult,
    RepositoryCodeInventory,
)
from .models import (
    CodeGraph,
    EdgeType,
    GraphEdge,
    GraphNode,
    NodeType,
)


class KnowledgeGraphBuilder:
    """
    Build a repository knowledge graph from analyzer output.

    Design principles:

        - deterministic node IDs
        - duplicate-safe nodes and edges
        - immutable graph output
        - parser-independent implementation
        - O(n) indexing where practical
        - unresolved calls preserved for resolver.py
        - local import resolution during graph construction
    """

    def __init__(self) -> None:
        self.logger = logging.getLogger(
            f"{__name__}.{self.__class__.__name__}"
        )

        self._nodes: dict[str, GraphNode] = {}

        self._edges: dict[
            tuple[str, str, EdgeType],
            GraphEdge,
        ] = {}

        # --------------------------------------------------------------
        # Indexes
        # --------------------------------------------------------------

        self._file_nodes: dict[
            Path,
            str,
        ] = {}

        self._entity_nodes: dict[
            tuple[Path, str, str],
            str,
        ] = {}

        self._symbol_index: dict[
            str,
            set[str],
        ] = defaultdict(set)

    # ==================================================================
    # Public API
    # ==================================================================

    def build(
        self,
        inventory: RepositoryCodeInventory,
        repository_root: Path | None = None,
    ) -> CodeGraph:
        """
        Build a CodeGraph from repository analysis output.

        Args:
            inventory:
                RepositoryCodeInventory generated by RepositoryCodeAnalyzer.

            repository_root:
                Optional repository root used to create a repository node.

        Returns:
            Immutable CodeGraph.
        """

        self._reset()

        # --------------------------------------------------------------
        # Repository
        # --------------------------------------------------------------

        if repository_root is not None:
            self._add_repository_node(
                repository_root.resolve()
            )

        # --------------------------------------------------------------
        # First pass:
        #
        # Create all files and entities before attempting to resolve
        # imports, exports, or calls.
        # --------------------------------------------------------------

        for result in inventory.files:
            self._add_file(result)

        # --------------------------------------------------------------
        # Second pass:
        #
        # Relationships can now safely reference every known symbol.
        # --------------------------------------------------------------

        for result in inventory.files:

            self._add_imports(result)

            self._add_exports(result)

            self._add_calls(result)

        graph = CodeGraph(
            nodes=tuple(
                sorted(
                    self._nodes.values(),
                    key=lambda node: node.id,
                )
            ),
            edges=tuple(
                sorted(
                    self._edges.values(),
                    key=lambda edge: (
                        edge.source_id,
                        edge.edge_type.value,
                        edge.target_id,
                    ),
                )
            ),
        )

        self.logger.info(
            "Knowledge graph built: %d nodes | %d edges",
            graph.node_count,
            graph.edge_count,
        )

        return graph

    # ==================================================================
    # Repository
    # ==================================================================

    def _add_repository_node(
        self,
        repository_root: Path,
    ) -> None:
        """Create the root repository node."""

        node_id = self._repository_node_id(
            repository_root
        )

        self._add_node(
            GraphNode(
                id=node_id,
                node_type=NodeType.REPOSITORY,
                name=repository_root.name,
                file_path=repository_root,
                qualified_name=repository_root.name,
            )
        )

    # ==================================================================
    # Files
    # ==================================================================

    def _add_file(
        self,
        result: FileAnalysisResult,
    ) -> None:
        """Create a graph node for an analyzed source file."""

        file_path = result.file_path

        node_id = self._file_node_id(
            file_path
        )

        self._file_nodes[
            file_path
        ] = node_id

        self._add_node(
            GraphNode(
                id=node_id,
                node_type=NodeType.FILE,
                name=file_path.name,
                file_path=file_path,
                qualified_name=file_path.as_posix(),
                metadata={
                    "entities": len(result.entities),
                    "imports": len(result.imports),
                    "exports": len(result.exports),
                    "calls": len(result.calls),
                    "syntax_errors": (
                        result.has_syntax_errors
                    ),
                },
            )
        )

        for entity in result.entities:

            self._add_entity(
                entity=entity,
                parent_file=node_id,
            )

    # ==================================================================
    # Entities
    # ==================================================================

    def _add_entity(
        self,
        entity: CodeEntity,
        parent_file: str,
    ) -> None:
        """Convert a CodeEntity into a graph node."""

        node_type = self._map_entity_type(
            entity.entity_type
        )

        if node_type is None:
            return

        node_id = self._entity_node_id(
            entity
        )

        # --------------------------------------------------------------
        # Entity index
        # --------------------------------------------------------------

        self._entity_nodes[
            (
                entity.file_path,
                entity.qualified_name,
                entity.entity_type.value,
            )
        ] = node_id

        # --------------------------------------------------------------
        # Symbol indexes
        # --------------------------------------------------------------

        self._symbol_index[
            entity.name
        ].add(node_id)

        self._symbol_index[
            entity.qualified_name
        ].add(node_id)

        # --------------------------------------------------------------
        # Node
        # --------------------------------------------------------------

        self._add_node(
            GraphNode(
                id=node_id,
                node_type=node_type,
                name=entity.name,
                file_path=entity.file_path,
                qualified_name=entity.qualified_name,
                metadata={
                    "entity_type": (
                        entity.entity_type.value
                    ),
                    "start_line": (
                        entity.location.start_line
                    ),
                    "start_column": (
                        entity.location.start_column
                    ),
                    "end_line": (
                        entity.location.end_line
                    ),
                    "end_column": (
                        entity.location.end_column
                    ),
                    "parent": entity.parent,
                    "parameters": entity.parameters,
                    "is_async": entity.is_async,
                    "has_source": (
                        entity.source is not None
                    ),
                },
            )
        )

        # --------------------------------------------------------------
        # FILE -> ENTITY
        # --------------------------------------------------------------

        self._add_edge(
            GraphEdge(
                source_id=parent_file,
                target_id=node_id,
                edge_type=EdgeType.CONTAINS,
            )
        )

    # ==================================================================
    # Imports
    # ==================================================================

    def _add_imports(
        self,
        result: FileAnalysisResult,
    ) -> None:
        """
        Create file-level and symbol-level IMPORTS relationships.

        Example:

            OrderPage.jsx
                |
                | IMPORTS
                v
            api.js
                |
                | defines
                v
            createOrder
        """

        source_file_id = self._file_nodes.get(
            result.file_path
        )

        if source_file_id is None:
            return

        for import_ref in result.imports:

            # ----------------------------------------------------------
            # Resolve imported module.
            # ----------------------------------------------------------

            target_file_id = (
                self._resolve_import_target(
                    import_ref
                )
            )

            # ----------------------------------------------------------
            # External package.
            # ----------------------------------------------------------

            if target_file_id is None:

                target_file_id = (
                    self._external_module_id(
                        import_ref.source
                    )
                )

                self._add_node(
                    GraphNode(
                        id=target_file_id,
                        node_type=NodeType.EXTERNAL_MODULE,
                        name=import_ref.source,
                        qualified_name=import_ref.source,
                        metadata={
                            "module": import_ref.source,
                        },
                    )
                )

            # ----------------------------------------------------------
            # File-level import.
            # ----------------------------------------------------------

            self._add_edge(
                GraphEdge(
                    source_id=source_file_id,
                    target_id=target_file_id,
                    edge_type=EdgeType.IMPORTS,
                    metadata={
                        "source": import_ref.source,
                        "line": (
                            import_ref.location.start_line
                        ),
                        "imported_names": (
                            import_ref.imported_names
                        ),
                    },
                )
            )

            # ----------------------------------------------------------
            # Symbol-level imports.
            # ----------------------------------------------------------

            for imported_name in (
                import_ref.imported_names
            ):

                symbol_id = (
                    self._find_imported_symbol(
                        target_file_id=target_file_id,
                        imported_name=imported_name,
                    )
                )

                if symbol_id is None:
                    continue

                self._add_edge(
                    GraphEdge(
                        source_id=source_file_id,
                        target_id=symbol_id,
                        edge_type=EdgeType.IMPORTS,
                        metadata={
                            "source": import_ref.source,
                            "symbol": imported_name,
                            "line": (
                                import_ref.location.start_line
                            ),
                            "resolved": True,
                        },
                    )
                )

    def _resolve_import_target(
        self,
        import_ref: ImportReference,
    ) -> str | None:
        """
        Resolve a local relative import to an analyzed file.

        Examples:

            ./api
            ./api.js
            ../services/api
            ../components/CardPaymentModal
            ./components/index.js
        """

        source = import_ref.source

        # Only resolve local relative imports.
        if not source.startswith("."):
            return None

        current_file = import_ref.file_path

        candidate = Path(
            current_file.parent,
            source,
        )

        normalized_candidate = Path(
            os.path.normpath(
                candidate.as_posix()
            )
        )

        candidates = (
            normalized_candidate,
            normalized_candidate.with_suffix(".js"),
            normalized_candidate.with_suffix(".jsx"),
            normalized_candidate.with_suffix(".mjs"),
            normalized_candidate / "index.js",
            normalized_candidate / "index.jsx",
            normalized_candidate / "index.mjs",
        )

        for path in candidates:

            normalized_path = Path(
                os.path.normpath(
                    path.as_posix()
                )
            )

            node_id = self._file_nodes.get(
                normalized_path
            )

            if node_id is not None:
                return node_id

        return None
    def _find_imported_symbol(
        self,
        target_file_id: str,
        imported_name: str,
    ) -> str | None:
        """
        Find a symbol defined inside the imported file.

        Resolution is restricted to the target file.

        This prevents a symbol with the same name in another file from
        being selected accidentally.
        """

        target_file = self._nodes.get(
            target_file_id
        )

        if target_file is None:
            return None

        target_path = target_file.file_path

        if target_path is None:
            return None

        matches = self._symbol_index.get(
            imported_name,
            set(),
        )

        candidates: list[str] = []

        for node_id in matches:

            node = self._nodes.get(
                node_id
            )

            if node is None:
                continue

            if node.file_path != target_path:
                continue

            if node.node_type not in {
                NodeType.FUNCTION,
                NodeType.METHOD,
                NodeType.CLASS,
                NodeType.COMPONENT,
                NodeType.VARIABLE,
            }:
                continue

            candidates.append(
                node_id
            )

        # Resolve only if exactly one definition exists.
        if len(candidates) == 1:
            return candidates[0]

        return None

    # ==================================================================
    # Exports
    # ==================================================================

    def _add_exports(
        self,
        result: FileAnalysisResult,
    ) -> None:
        """Create EXPORTS relationships."""

        file_id = self._file_nodes.get(
            result.file_path
        )

        if file_id is None:
            return

        for export_ref in result.exports:

            target_id = (
                self._find_exported_entity(
                    result.file_path,
                    export_ref.source,
                )
            )

            if target_id is None:
                continue

            self._add_edge(
                GraphEdge(
                    source_id=file_id,
                    target_id=target_id,
                    edge_type=EdgeType.EXPORTS,
                    metadata={
                        "source": export_ref.source,
                        "line": (
                            export_ref.location.start_line
                        ),
                        "resolved": True,
                    },
                )
            )

    def _find_exported_entity(
        self,
        file_path: Path,
        export_source: str,
    ) -> str | None:
        """
        Resolve an export declaration to an entity in the same file.
        """

        candidates = (
            export_source,
            export_source.removeprefix(
                "default "
            ),
        )

        for name in candidates:

            matches = self._symbol_index.get(
                name,
                set(),
            )

            if not matches:
                continue

            file_matches: list[str] = []

            for node_id in matches:

                node = self._nodes.get(
                    node_id
                )

                if node is None:
                    continue

                if node.file_path != file_path:
                    continue

                file_matches.append(
                    node_id
                )

            if len(file_matches) == 1:
                return file_matches[0]

        return None

    # ==================================================================
    # Calls
    # ==================================================================

    def _add_calls(
        self,
        result: FileAnalysisResult,
    ) -> None:
        """
        Create CALLS relationships.

        Calls that cannot be resolved locally are represented as
        unresolved VARIABLE nodes and can later be handled by
        resolver.py.
        """

        for call in result.calls:

            caller_id = self._resolve_caller(
                call
            )

            if caller_id is None:

                caller_id = self._file_nodes.get(
                    result.file_path
                )

            if caller_id is None:
                continue

            target_id = self._resolve_callee(
                call
            )

            resolved = target_id is not None

            # ----------------------------------------------------------
            # Preserve unresolved symbol.
            # ----------------------------------------------------------

            if target_id is None:

                target_id = (
                    self._unresolved_symbol_id(
                        call.callee
                    )
                )

                self._add_node(
                    GraphNode(
                        id=target_id,
                        node_type=NodeType.VARIABLE,
                        name=call.callee,
                        qualified_name=call.callee,
                        metadata={
                            "resolved": False,
                        },
                    )
                )

            # ----------------------------------------------------------
            # CALL edge.
            # ----------------------------------------------------------

            self._add_edge(
                GraphEdge(
                    source_id=caller_id,
                    target_id=target_id,
                    edge_type=EdgeType.CALLS,
                    metadata={
                        "line": (
                            call.location.start_line
                        ),
                        "resolved": resolved,
                    },
                )
            )

    def _resolve_caller(
        self,
        call: CallReference,
    ) -> str | None:
        """Resolve the function/method containing a call."""

        matches = self._symbol_index.get(
            call.caller,
            set(),
        )

        if not matches:
            return None

        for node_id in matches:

            node = self._nodes.get(
                node_id
            )

            if node is None:
                continue

            if node.file_path != call.file_path:
                continue

            if node.node_type not in {
                NodeType.FUNCTION,
                NodeType.METHOD,
                NodeType.COMPONENT,
            }:
                continue

            return node_id

        return None

    def _resolve_callee(
        self,
        call: CallReference,
    ) -> str | None:
        """
        Resolve a call target when exactly one matching symbol exists
        in the same file.
        """

        matches = self._symbol_index.get(
            call.callee,
            set(),
        )

        if not matches:
            return None

        same_file_matches: list[str] = []

        for node_id in matches:

            node = self._nodes.get(
                node_id
            )

            if node is None:
                continue

            if node.file_path != call.file_path:
                continue

            if node.node_type not in {
                NodeType.FUNCTION,
                NodeType.METHOD,
                NodeType.CLASS,
                NodeType.COMPONENT,
                NodeType.VARIABLE,
            }:
                continue

            same_file_matches.append(
                node_id
            )

        if len(same_file_matches) == 1:
            return same_file_matches[0]

        # Cross-file calls are resolved later by resolver.py.
        return None

    # ==================================================================
    # Internal graph operations
    # ==================================================================

    def _add_node(
        self,
        node: GraphNode,
    ) -> None:
        """Add a node if it does not already exist."""

        self._nodes.setdefault(
            node.id,
            node,
        )

    def _add_edge(
        self,
        edge: GraphEdge,
    ) -> None:
        """Add a unique directed graph edge."""

        key = (
            edge.source_id,
            edge.target_id,
            edge.edge_type,
        )

        self._edges.setdefault(
            key,
            edge,
        )

    def _reset(self) -> None:
        """Reset builder state before constructing a new graph."""

        self._nodes.clear()
        self._edges.clear()

        self._file_nodes.clear()
        self._entity_nodes.clear()
        self._symbol_index.clear()

    # ==================================================================
    # Node ID generation
    # ==================================================================

    @staticmethod
    def _repository_node_id(
        repository_root: Path,
    ) -> str:
        """Generate a deterministic repository node ID."""

        return (
            "repository:"
            f"{repository_root.as_posix()}"
        )

    @staticmethod
    def _file_node_id(
        file_path: Path,
    ) -> str:
        """Generate a deterministic file node ID."""

        return (
            "file:"
            f"{file_path.as_posix()}"
        )

    @staticmethod
    def _entity_node_id(
        entity: CodeEntity,
    ) -> str:
        """Generate a deterministic entity node ID."""

        return (
            f"{entity.entity_type.value}:"
            f"{entity.file_path.as_posix()}:"
            f"{entity.qualified_name}:"
            f"{entity.location.start_line}"
        )

    @staticmethod
    def _external_module_id(
        module: str,
    ) -> str:
        """Generate an external module node ID."""

        return f"external:{module}"

    @staticmethod
    def _unresolved_symbol_id(
        symbol: str,
    ) -> str:
        """Generate an unresolved symbol node ID."""

        return f"unresolved:{symbol}"

    # ==================================================================
    # Entity mapping
    # ==================================================================

    @staticmethod
    def _map_entity_type(
        entity_type: CodeEntityType,
    ) -> NodeType | None:
        """Map analyzer entity types to graph node types."""

        mapping = {
            CodeEntityType.FUNCTION: NodeType.FUNCTION,
            CodeEntityType.METHOD: NodeType.METHOD,
            CodeEntityType.CLASS: NodeType.CLASS,
            CodeEntityType.COMPONENT: NodeType.COMPONENT,
            CodeEntityType.VARIABLE: NodeType.VARIABLE,
        }

        return mapping.get(
            entity_type
        )